# Generated by Django 5.2 on 2025-09-30 20:46

import signature_pad.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', signature_pad.fields.SignaturePadField(blank=True, null=True)),
            ],
        ),
    ]
