# Generated by Django 5.2 on 2025-09-30 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_document_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Signature',
        ),
    ]
