# Generated by Django 5.2 on 2025-09-30 22:15

import signature_pad.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0003_rename_document_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='signature',
            field=signature_pad.fields.SignaturePadField(null=True),
        ),
    ]
