# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AcClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_class', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=10)),
                ('aircraft_registration', models.CharField(blank=True, max_length=10, null=True)),
                ('turbine', models.NullBooleanField()),
                ('piston', models.NullBooleanField()),
                ('requires_type', models.NullBooleanField()),
                ('tailwheel', models.NullBooleanField()),
                ('compleks', models.NullBooleanField()),
                ('high_performance', models.NullBooleanField()),
                ('is_default', models.NullBooleanField()),
                ('ac_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.AcCategory')),
                ('ac_class', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.AcClass')),
            ],
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('aircraft_ident', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=50)),
                ('legs', models.PositiveIntegerField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('landings_day', models.PositiveIntegerField(blank=True, null=True)),
                ('landings_night', models.PositiveIntegerField(blank=True, null=True)),
                ('night', models.FloatField(blank=True, null=True)),
                ('instrument', models.FloatField(blank=True, null=True)),
                ('cross_country', models.NullBooleanField()),
                ('second_in_command', models.NullBooleanField()),
                ('pilot_in_command', models.NullBooleanField()),
                ('simulated_instrument', models.FloatField(blank=True, null=True)),
                ('instructor', models.NullBooleanField()),
                ('dual', models.NullBooleanField()),
                ('remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('simulator', models.NullBooleanField()),
                ('solo', models.NullBooleanField()),
                ('aircraft', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft')),
                ('approaches', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Approach')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
