# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20170118_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='ac_category',
            new_name='aircraft_category',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='ac_class',
            new_name='aircraft_class',
        ),
    ]
