# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20170118_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='aircraft_ident',
            new_name='aircraft_registration',
        ),
    ]
