# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20170119_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_91', models.NullBooleanField()),
            ],
        ),
    ]
