# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0035_auto_20170507_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='duration',
            new_name='total_time',
        ),
    ]
