# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0037_auto_20170507_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='aircraft_type',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
