# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0044_auto_20170510_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='approaches',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Approach'),
        ),
        migrations.AddField(
            model_name='total',
            name='cross_country',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='total',
            name='dual',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='total',
            name='instructor',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='total',
            name='instrument',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='landings_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='landings_night',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='night',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='remarks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='second_in_command',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='total',
            name='simulated_instrument',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='simulator',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='total',
            name='solo',
            field=models.NullBooleanField(),
        ),
    ]
