# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0049_auto_20170511_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='total',
            name='dual',
            field=models.FloatField(null=True),
        ),
    ]
