# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0051_auto_20170511_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='landings_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
