# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0056_auto_20170517_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='last_12m',
        ),
        migrations.RemoveField(
            model_name='total',
            name='last_30',
        ),
        migrations.RemoveField(
            model_name='total',
            name='last_60',
        ),
        migrations.RemoveField(
            model_name='total',
            name='last_6m',
        ),
        migrations.RemoveField(
            model_name='total',
            name='last_90',
        ),
    ]
