# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0059_auto_20170520_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=10)),
                ('hours', models.FloatField(blank=True, default=0)),
                ('pilot_in_command', models.FloatField(blank=True, default=0, null=True)),
                ('second_in_command', models.FloatField(blank=True, default=0, null=True)),
                ('cross_country', models.FloatField(blank=True, default=0, null=True)),
                ('instructor', models.FloatField(blank=True, default=0, null=True)),
                ('dual', models.FloatField(blank=True, default=0, null=True)),
                ('solo', models.FloatField(blank=True, default=0, null=True)),
                ('instrument', models.FloatField(blank=True, default=0, null=True)),
                ('night', models.FloatField(blank=True, default=0, null=True)),
                ('simulated_instrument', models.FloatField(blank=True, default=0, null=True)),
                ('simulator', models.FloatField(blank=True, default=0, null=True)),
                ('landings_day', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('landings_night', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('approaches', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Approach')),
            ],
        ),
    ]
