# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0062_auto_20170522_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='approaches',
        ),
    ]
