# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0065_auto_20170523_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='landings_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='total_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
