# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0067_auto_20170523_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='total',
            options={'ordering': ['total_time']},
        ),
        migrations.AddField(
            model_name='stat',
            name='last_flown',
            field=models.DateField(blank=True, null=True),
        ),
    ]
