# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0070_auto_20170525_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='_30_days',
            new_name='last_30',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='_12_months',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='_60_days',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='_6_months',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='_90_days',
        ),
        migrations.AddField(
            model_name='stat',
            name='last_60',
            field=models.FloatField(blank=True, null=True, verbose_name='60'),
        ),
        migrations.AddField(
            model_name='stat',
            name='last_90',
            field=models.FloatField(blank=True, null=True, verbose_name='90'),
        ),
        migrations.AddField(
            model_name='stat',
            name='months_12',
            field=models.FloatField(blank=True, null=True, verbose_name='12mo'),
        ),
        migrations.AddField(
            model_name='stat',
            name='months_6',
            field=models.FloatField(blank=True, null=True, verbose_name='6mo'),
        ),
    ]
