# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0071_auto_20170525_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='months_6',
            new_name='last_180',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='months_12',
            new_name='last_yr',
        ),
        migrations.AlterField(
            model_name='stat',
            name='approaches',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Approach', verbose_name='Appr'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='cross_country',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='XC'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='instructor',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CFI'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='instrument',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Inst'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='landings_day',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='LDG Day'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='landings_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='LDG Night'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='pilot_in_command',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='PIC'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='second_in_command',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='SIC'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='simulated_instrument',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Sim Inst'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='simulator',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Sim'),
        ),
    ]
