# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0076_total_amel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='is_default',
            new_name='asel',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_category',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_class',
        ),
        migrations.DeleteModel(
            name='AircraftCategory',
        ),
        migrations.DeleteModel(
            name='AircraftClass',
        ),
    ]
