# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0079_remove_total_amel'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='label',
            field=models.CharField(default='', max_length=20),
        ),
    ]
