# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0082_auto_20170614_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='total_type',
        ),
    ]
