# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0083_remove_total_total_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='total_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
