# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0084_total_total_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='total_type',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='total',
            name='total_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Time'),
        ),
    ]
