# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0087_byseat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BySeat',
            new_name='Power',
        ),
    ]
