# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0097_auto_20170711_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement', models.CharField(default='', max_length=30)),
                ('tailwheel', models.FloatField(blank=True, default=0, null=True, verbose_name='Tailwheel')),
                ('high_performance', models.FloatField(blank=True, default=0, null=True, verbose_name='High Performance')),
                ('compleks', models.FloatField(blank=True, default=0, null=True, verbose_name='Complex')),
            ],
        ),
    ]
