# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0103_auto_20170712_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='piston',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='turbine',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
