# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0109_auto_20170712_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='small',
            field=models.NullBooleanField(verbose_name='Small <12.5k lbs'),
        ),
    ]
