# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0112_aircraft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='compleks',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Complex'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='heavy',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Heavy >300k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='high_performance',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='large',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Large 41k-300k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='medium',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Meduim 12.5-41k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='piston',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='requires_type',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='small',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Small <12.5k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='superr',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Super'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tailwheel',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='turbine',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
