# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0127_auto_20170810_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapdata',
            old_name='altitude',
            new_name='elevation',
        ),
        migrations.AddField(
            model_name='mapdata',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
