# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0132_mapdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdata',
            options={'ordering': ['city', 'state', 'country'], 'verbose_name_plural': 'Map Data'},
        ),
    ]
