# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0140_auto_20170827_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='total',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='city',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='country',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='state',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='power',
            name='role',
            field=models.CharField(db_index=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='regs',
            name='reg_type',
            field=models.CharField(db_index=True, default='', max_length=5, verbose_name='Reg'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='last_flown',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='total_time',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True, verbose_name='Time'),
        ),
    ]
