# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0150_auto_20171111_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='point_json',
            new_name='geojson',
        ),
    ]
