# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0151_auto_20171116_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='geojson',
        ),
    ]
