# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0163_flight_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='geojson',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
