# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0170_flight_holding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='ydt',
            new_name='ytd',
        ),
    ]
