# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0174_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='error',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='error',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='tailnumber',
            name='error',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
