# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0183_auto_20180206_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='tailnumber_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duplicate_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='map_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
