# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0185_flight_crew_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='aircraft_error',
            new_name='aircraft_type_error',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='tailnumber_error',
            new_name='registration_error',
        ),
    ]
