# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0188_remove_tailnumber_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailnumber',
            name='tailnumber_error',
            field=models.NullBooleanField(),
        ),
    ]
