# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0189_tailnumber_tailnumber_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailnumber',
            old_name='tailnumber_error',
            new_name='registration_error',
        ),
    ]
