# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0195_remove_tailnumber_registration_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailnumber',
            name='aircraft',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft'),
        ),
    ]
