# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0198_auto_20180809_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailnumber',
            name='reg_error',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
