# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0222_auto_20181204_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailnumber',
            name='aircraft',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft'),
        ),
    ]
