# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-15 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0223_auto_20181207_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tailnumber',
            options={'ordering': ['aircraft', 'registration'], 'verbose_name_plural': 'Tailnumbers'},
        ),
    ]
