# Generated by Django 2.2.8 on 2020-01-31 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='', max_length=50)),
                ('medical_issue_date', models.DateField(blank=True, default=None, null=True)),
                ('first_class', models.BooleanField(default=False)),
                ('second_class', models.BooleanField(default=False)),
                ('third_class', models.BooleanField(default=False)),
                ('over_40', models.BooleanField(default=False)),
                ('free_access', models.BooleanField(default=False)),
                ('customer_id', models.CharField(blank=True, max_length=50)),
                ('subscription_id', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
                ('yearly', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('trial', models.BooleanField(default=False)),
                ('trial_expiring', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
