# Generated by Django 5.2 on 2025-07-30 17:06

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_alter_profile_medical_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medical_issue_date',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
