# Generated by Django 5.2 on 2025-07-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_profile_medical_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medical_issue_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
