# Generated by Django 5.2 on 2025-07-30 17:15


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_alter_profile_medical_issue_date'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE profile_profile SET medical_issue_date = CURRENT_DATE WHERE medical_issue_date IS NULL;",
            reverse_sql="UPDATE profile_profile SET medical_issue_date = NULL WHERE medical_issue_date = CURRENT_DATE;",
        ),
        migrations.AlterField(
            model_name='profile',
            name='medical_issue_date',
            field=models.DateField(
                null=False, blank=False, default=datetime.date.today),
        ),
    ]
