# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-24 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signature',
        ),
    ]
