# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-30 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='over_40',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_class',
            field=models.BooleanField(default=False),
        ),
    ]
