# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-30 01:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190530_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medical_issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
