# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-30 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_medical_issue_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='medical_issue_date',
            new_name='date',
        ),
    ]
