# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-30 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190530_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
