# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190530_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
