# Generated by Django 2.2.4 on 2019-08-23 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trial_end',
            field=models.DateField(default=datetime.date(2019, 8, 23), null=True),
        ),
    ]
