# Generated by Django 2.2.4 on 2019-08-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_trial_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date',
            new_name='medical_issue_date',
        ),
    ]
