# Generated by Django 2.2.4 on 2019-08-23 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trial_end',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 21, 18, 57, 536512, tzinfo=utc), null=True),
        ),
    ]
