# Generated by Django 2.2.4 on 2019-08-23 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190823_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trial_end',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 21, 19, 29, 976923, tzinfo=utc), null=True),
        ),
    ]
