# Generated by Django 2.2.4 on 2019-08-25 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190823_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trial_end',
            field=models.DateField(default=datetime.datetime(2019, 8, 25, 22, 46, 28, 373244, tzinfo=utc), null=True),
        ),
    ]
