# Generated by Django 2.2.4 on 2019-08-26 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190825_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trial_end',
            field=models.DateField(default=datetime.datetime(2019, 8, 26, 21, 34, 49, 400714, tzinfo=utc), null=True),
        ),
    ]
