# Generated by Django 2.2.4 on 2019-08-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190827_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medical_issue_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
