# Generated by Django 2.2.4 on 2019-08-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190827_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='trial_end',
            new_name='end_date',
        ),
    ]
