# Generated by Django 2.2.4 on 2019-09-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='admin',
            new_name='free_access',
        ),
    ]
