# Generated by Django 2.2.4 on 2019-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190901_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
