# Generated by Django 2.2.4 on 2019-09-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cancelled',
            new_name='canceled',
        ),
    ]
