# Generated by Django 2.2.4 on 2019-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190902_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
    ]
