# Generated by Django 2.2.4 on 2019-09-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_profile_monthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='yearly',
            field=models.BooleanField(default=False),
        ),
    ]
