# Generated by Django 2.2.8 on 2020-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_profile_yearly'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
