# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 14:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import flights.models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(db_index=True, max_length=10, unique=True)),
                ('turbine', models.NullBooleanField()),
                ('piston', models.NullBooleanField()),
                ('requires_type', models.NullBooleanField()),
                ('tailwheel', models.NullBooleanField()),
                ('simple', models.NullBooleanField()),
                ('compleks', models.NullBooleanField(verbose_name='Complex')),
                ('high_performance', models.NullBooleanField()),
                ('superr', models.NullBooleanField(verbose_name='Super')),
                ('heavy', models.NullBooleanField(verbose_name='Heavy >300k lbs')),
                ('large', models.NullBooleanField(verbose_name='Large 41k-300k lbs')),
                ('medium', models.NullBooleanField(verbose_name='Meduim 12.5-41k lbs')),
                ('small', models.NullBooleanField(verbose_name='Small <12.5k lbs')),
                ('light_sport', models.NullBooleanField(verbose_name='LSA <1320 lbs')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='aircraft/')),
                ('config_error', models.CharField(blank=True, max_length=100, null=True)),
                ('power_error', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_error', models.CharField(blank=True, max_length=100, null=True)),
                ('category_error', models.CharField(blank=True, max_length=100, null=True)),
                ('class_error', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['aircraft_type'],
            },
        ),
        migrations.CreateModel(
            name='AircraftCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Aircraft Categories',
            },
        ),
        migrations.CreateModel(
            name='AircraftClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_class', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Aircraft Classes',
            },
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach_type', models.CharField(choices=[('ILS', 'ILS'), ('CATII', 'CAT II'), ('CATIII', 'CAT III'), ('GPS', 'GPS'), ('RNAV', 'RNAV'), ('LOC', 'LOC'), ('VOR', 'VOR'), ('NDB', 'NDB'), ('LOC BC', 'LOC BC'), ('SDF', 'SDF'), ('LDA', 'LDA'), ('TACAN', 'TACAN'), ('MLS', 'MLS')], max_length=15, verbose_name='Approach Type')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number')),
            ],
            options={
                'verbose_name_plural': 'Approaches',
                'ordering': ['approach_type'],
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement', models.CharField(default='', max_length=30)),
                ('total', models.DecimalField(blank=True, db_index=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('route', models.CharField(max_length=50)),
                ('legs', models.PositiveIntegerField(null=True)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')])),
                ('landings_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='Day Ldg')),
                ('landings_night', models.PositiveIntegerField(blank=True, null=True, verbose_name='Night Ldg')),
                ('night', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')])),
                ('instrument', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')], verbose_name='Inst')),
                ('cross_country', models.NullBooleanField(verbose_name='XCountry')),
                ('second_in_command', models.NullBooleanField(verbose_name='SIC')),
                ('pilot_in_command', models.NullBooleanField(verbose_name='PIC')),
                ('simulated_instrument', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')], verbose_name='Sim Inst')),
                ('instructor', models.NullBooleanField(verbose_name='CFI')),
                ('dual', models.NullBooleanField()),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('simulator', models.NullBooleanField(verbose_name='Sim')),
                ('solo', models.NullBooleanField()),
                ('route_data', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('map_error', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicate_error', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft_type_error', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_error', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_error', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Aircraft')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold', models.BooleanField(default=False)),
                ('flight_object', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Flight', verbose_name='Flight')),
            ],
        ),
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('city', models.CharField(db_index=True, default='', max_length=50)),
                ('state', models.CharField(db_index=True, default='', max_length=50)),
                ('country', models.CharField(db_index=True, default='', max_length=50)),
                ('iata', models.CharField(db_index=True, default='', max_length=3)),
                ('icao', models.CharField(db_index=True, default='', max_length=4)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('elevation', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Map Data',
                'ordering': ['city', 'state', 'country'],
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, default='', max_length=5)),
                ('turbine', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('piston', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Power',
                'ordering': ['-role'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=50)),
                ('signature', models.FileField(upload_to=flights.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Regs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_type', models.CharField(db_index=True, default='', max_length=5, verbose_name='Reg')),
                ('pilot_in_command', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='PIC')),
                ('second_in_command', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='SIC')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Regs',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=10)),
                ('total_time', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, verbose_name='Time')),
                ('pilot_in_command', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='PIC')),
                ('second_in_command', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='SIC')),
                ('cross_country', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='XC')),
                ('instructor', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='CFI')),
                ('dual', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('solo', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('instrument', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Inst')),
                ('night', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('simulated_instrument', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Sim Inst')),
                ('simulator', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Sim')),
                ('landings_day', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Day Ldg')),
                ('landings_night', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Night Ldg')),
                ('last_flown', models.DateField(blank=True, db_index=True, null=True)),
                ('last_30', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='30')),
                ('last_60', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='60')),
                ('last_90', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='90')),
                ('last_180', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='6mo')),
                ('last_yr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='12mo')),
                ('last_2yr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='24')),
                ('ytd', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='YDT')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_flown'],
            },
        ),
        migrations.CreateModel(
            name='TailNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(db_index=True, max_length=10, unique=True)),
                ('is_121', models.NullBooleanField()),
                ('is_135', models.NullBooleanField()),
                ('is_91', models.NullBooleanField()),
                ('reg_error', models.CharField(blank=True, max_length=50, null=True)),
                ('aircraft', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tailnumbers',
                'ordering': ['aircraft', 'registration'],
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default='', max_length=20)),
                ('total_time', models.DecimalField(blank=True, db_index=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Time')),
                ('pilot_in_command', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='PIC')),
                ('second_in_command', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='SIC')),
                ('cross_country', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='XC')),
                ('instructor', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='CFI')),
                ('dual', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('solo', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('instrument', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Inst')),
                ('night', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('simulated_instrument', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Sim Inst')),
                ('simulator', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Sim')),
                ('landings_day', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Day Ldg')),
                ('landings_night', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Night Ldg')),
                ('landings_total', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Ldg')),
                ('last_flown', models.DateField(blank=True, null=True)),
                ('last_30', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='30')),
                ('last_60', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='60')),
                ('last_90', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='90')),
                ('last_180', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='6mo')),
                ('last_yr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='12mo')),
                ('last_2yr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='24')),
                ('ytd', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='YDT')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_time'],
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(default='', max_length=20)),
                ('total', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weight',
            },
        ),
        migrations.AlterIndexTogether(
            name='mapdata',
            index_together=set([('iata', 'icao')]),
        ),
        migrations.AddField(
            model_name='flight',
            name='registration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.TailNumber'),
        ),
        migrations.AddField(
            model_name='flight',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approach',
            name='flight_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Flight', verbose_name='Flight'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.AircraftCategory'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.AircraftClass'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='flight',
            index_together=set([('route', 'date', 'duration')]),
        ),
    ]
