# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20190610_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['user', 'aircraft_type'], 'verbose_name_plural': 'Aircraft'},
        ),
        migrations.AlterModelOptions(
            name='endorsement',
            options={'ordering': ['user', '-total']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['user', '-date']},
        ),
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['user', '-role'], 'verbose_name_plural': 'Power'},
        ),
        migrations.AlterModelOptions(
            name='regs',
            options={'ordering': ['user'], 'verbose_name_plural': 'Regs'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['user', '-last_flown']},
        ),
        migrations.AlterModelOptions(
            name='tailnumber',
            options={'ordering': ['user', 'aircraft', 'registration'], 'verbose_name_plural': 'Tailnumbers'},
        ),
        migrations.AlterModelOptions(
            name='total',
            options={'ordering': ['user', '-total_time']},
        ),
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['user'], 'verbose_name_plural': 'Weight'},
        ),
    ]
