# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20190620_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='flight_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Flight', verbose_name='Flight'),
        ),
        migrations.AlterField(
            model_name='regs',
            name='reg_type',
            field=models.CharField(db_index=True, default='', max_length=5),
        ),
    ]
