# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-20 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20190709_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='legs',
        ),
    ]
