# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20190722_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='registration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flights.TailNumber'),
        ),
    ]
