# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-26 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0008_auto_20190722_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.DecimalField(blank=True, db_index=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Time')),
                ('pilot_in_command', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='PIC')),
                ('second_in_command', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='SIC')),
                ('cross_country', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='XC')),
                ('instructor', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='CFI')),
                ('dual', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('solo', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('instrument', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Inst')),
                ('night', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True)),
                ('simulated_instrument', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Sim Inst')),
                ('simulator', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Sim')),
                ('landings_day', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Day Ldg')),
                ('landings_night', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Night Ldg')),
                ('landings_total', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Ldg')),
                ('last_flown', models.DateField(blank=True, null=True)),
                ('last_30', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='30')),
                ('last_60', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='60')),
                ('last_90', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='90')),
                ('last_180', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='6mo')),
                ('last_yr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='12mo')),
                ('last_2yr', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='24')),
                ('ytd', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='YDT')),
                ('aircraft_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft')),
                ('registration', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flights.TailNumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
