# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-26 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_bulkentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkentry',
            name='registration',
        ),
    ]
