# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-27 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_auto_20190726_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkentry',
            name='aircraft_type',
        ),
    ]
