# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_registration_aircraft_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='aircraft_type',
        ),
        migrations.AddField(
            model_name='flight',
            name='is_121',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_135',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_91',
            field=models.NullBooleanField(),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
