# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_auto_20170215_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10)),
                ('is_121', models.NullBooleanField()),
                ('is_135', models.NullBooleanField()),
                ('is_91', models.NullBooleanField()),
                ('aircraft', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft')),
            ],
        ),
    ]
