# Generated by Django 2.2.4 on 2019-08-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_auto_20190819_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='hold',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
