# Generated by Django 2.2.4 on 2019-08-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_auto_20190819_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['pk', 'user', '-date']},
        ),
    ]
