# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0018_auto_20170216_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_registration',
        ),
    ]
