# Generated by Django 2.2.4 on 2019-08-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0020_auto_20190820_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['pk']},
        ),
    ]
