# Generated by Django 2.2.4 on 2019-08-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0021_auto_20190820_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['pk', '-date']},
        ),
    ]
