# Generated by Django 2.2.4 on 2019-08-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0022_auto_20190822_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-date', 'pk']},
        ),
    ]
