# Generated by Django 2.2.4 on 2019-09-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0023_auto_20190822_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkEntry',
        ),
    ]
