# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0025_auto_20170223_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='dummy_reg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
