# Generated by Django 2.2.4 on 2019-09-18 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0026_auto_20190918_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Import',
            new_name='Imported',
        ),
        migrations.AlterModelOptions(
            name='imported',
            options={'verbose_name_plural': 'Imported'},
        ),
    ]
