# Generated by Django 2.2.4 on 2019-09-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0027_auto_20190918_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='imported',
            name='is_121',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='imported',
            name='is_135',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='imported',
            name='is_91',
            field=models.NullBooleanField(),
        ),
    ]
