# Generated by Django 2.2.4 on 2019-10-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0030_auto_20191003_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='ac_category',
            field=models.CharField(choices=[('Airplane', 'Airplane'), ('Rotorcraft', 'Rotorcraft')], default='', max_length=30, verbose_name='Aircraft Category'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='ac_class',
            field=models.CharField(choices=[('SEL', 'Single-Engine Land'), ('MEL', 'Multi-Engine Land'), ('SES', 'Single-Engine Sea'), ('MES', 'Mult-Engine Sea'), ('HELO', 'Helicopter'), ('GYRO', 'Gyroplane')], default='', max_length=30, verbose_name='Aircraft Class'),
        ),
    ]
