# Generated by Django 2.2.4 on 2019-10-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0031_auto_20191016_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_category',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_class',
        ),
    ]
