# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0033_auto_20170506_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='id',
        ),
        migrations.AddField(
            model_name='total',
            name='aircraft_type',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
