# Generated by Django 2.2.4 on 2019-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0035_auto_20191108_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approach',
            name='approach_type',
            field=models.CharField(choices=[('', 'None'), ('ILS', 'ILS'), ('CATII', 'CAT II'), ('CATIII', 'CAT III'), ('GPS', 'GPS'), ('RNAV', 'RNAV'), ('LOC', 'LOC'), ('VOR', 'VOR'), ('NDB', 'NDB'), ('LOC BC', 'LOC BC'), ('SDF', 'SDF'), ('LDA', 'LDA'), ('TACAN', 'TACAN'), ('MLS', 'MLS')], max_length=15, verbose_name='Approach Type'),
        ),
    ]
