# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0036_auto_20170507_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='aircraft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flights.Aircraft'),
        ),
    ]
