# Generated by Django 2.2.4 on 2019-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0037_auto_20191112_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='turbine',
            field=models.BooleanField(default=False),
        ),
    ]
