# Generated by Django 2.2.4 on 2019-11-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0038_auto_20191125_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='compleks',
            field=models.BooleanField(default=False, verbose_name='Complex'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='high_performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='piston',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='requires_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='simple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tailwheel',
            field=models.BooleanField(default=False),
        ),
    ]
