# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0038_auto_20170507_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='total',
            name='aircraft_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft'),
        ),
    ]
