# Generated by Django 2.2.4 on 2019-11-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0041_auto_20191125_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailnumber',
            name='reg_error',
        ),
    ]
