# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0043_total_pilot_in_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='pilot_in_command',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='total',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
