# Generated by Django 2.2.4 on 2019-11-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0043_tailnumber_reg_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailnumber',
            name='reg_error',
        ),
    ]
