# Generated by Django 2.2.8 on 2020-01-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0044_remove_tailnumber_reg_error'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tailnumber',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tailnumber',
            constraint=models.UniqueConstraint(fields=('user', 'registration'), name='unique tailnumber'),
        ),
    ]
