# Generated by Django 3.1.1 on 2020-09-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0046_auto_20200904_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cross_country',
            field=models.BooleanField(blank=True, default=False, verbose_name='XCountry'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dual',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instructor',
            field=models.BooleanField(blank=True, default=False, verbose_name='CFI'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='pilot_in_command',
            field=models.BooleanField(blank=True, default=False, verbose_name='PIC'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='second_in_command',
            field=models.BooleanField(blank=True, default=False, verbose_name='SIC'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulator',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sim'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='solo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
