# Generated by Django 3.1.1 on 2021-05-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0049_auto_20200904_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='json_route_data',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
