# Generated by Django 3.1.1 on 2021-05-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0050_flight_json_route_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='json_route_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
