# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0050_auto_20170511_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='cross_country',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='dual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='instructor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='pilot_in_command',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='second_in_command',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='solo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
