# Generated by Django 3.1.1 on 2021-05-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0051_auto_20210516_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='app_airport_detail',
            field=models.CharField(default='', max_length=500),
        ),
    ]
