# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0052_total_landings_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='simulator',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
