# Generated by Django 3.1.1 on 2021-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0053_auto_20210516_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='app_airport_detail',
            field=models.JSONField(default=str),
        ),
    ]
