# Generated by Django 3.1.1 on 2021-05-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0054_auto_20210516_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='app_airport_detail',
            new_name='app_lines',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='app_route_detail',
            new_name='app_markers',
        ),
    ]
