# Generated by Django 3.1.1 on 2021-05-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0055_auto_20210521_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='app_lines',
            new_name='app_polylines',
        ),
    ]
