# Generated by Django 3.1.1 on 2021-08-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0056_auto_20210526_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='app_markers',
            field=models.JSONField(blank=True, default=str),
        ),
        migrations.AlterField(
            model_name='flight',
            name='app_polylines',
            field=models.JSONField(blank=True, default=str),
        ),
    ]
