# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0057_auto_20170517_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'ordering': ['aircraft_type']},
        ),
        migrations.AlterModelOptions(
            name='approach',
            options={'ordering': ['approach_type']},
        ),
        migrations.AlterModelOptions(
            name='tailnumber',
            options={'ordering': ['aircraft', 'registration']},
        ),
        migrations.AlterModelOptions(
            name='total',
            options={'ordering': ['aircraft_type']},
        ),
        migrations.RemoveField(
            model_name='total',
            name='landings_total',
        ),
    ]
