# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0058_auto_20170520_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='total_time',
            new_name='hours',
        ),
    ]
