# Generated by Django 3.1.1 on 2021-10-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0059_auto_20211016_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='hold',
            field=models.BooleanField(blank=True, default=False, verbose_name='Hold'),
        ),
    ]
