# Generated by Django 5.2 on 2025-07-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0060_flight_hold'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='flight',
            new_name='flights_fli_route_caa1c4_idx',
            old_fields=('route', 'date', 'duration'),
        ),
        migrations.AddIndex(
            model_name='mapdata',
            index=models.Index(fields=['iata'], name='flights_map_iata_edaf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='mapdata',
            index=models.Index(fields=['icao'], name='flights_map_icao_b253a2_idx'),
        ),
    ]
