# Generated by Django 5.2 on 2025-07-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0061_rename_flight_route_date_duration_flights_fli_route_caa1c4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(),
        ),
    ]
