# Generated by Django 5.2 on 2025-07-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0062_alter_flight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
