# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0066_auto_20170523_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='landings_total',
        ),
        migrations.AddField(
            model_name='total',
            name='landings_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
