# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0074_auto_20170601_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='ydt',
            field=models.FloatField(blank=True, null=True, verbose_name='YDT'),
        ),
    ]
