# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0075_auto_20170601_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='amel',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
