# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0080_total_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='label',
            new_name='by_class',
        ),
    ]
