# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0081_auto_20170614_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='total',
            options={'ordering': ['-total_time']},
        ),
        migrations.RenameField(
            model_name='total',
            old_name='by_class',
            new_name='total_type',
        ),
        migrations.AlterField(
            model_name='total',
            name='cross_country',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='XC'),
        ),
        migrations.AlterField(
            model_name='total',
            name='instructor',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CFI'),
        ),
        migrations.AlterField(
            model_name='total',
            name='instrument',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Inst'),
        ),
        migrations.AlterField(
            model_name='total',
            name='pilot_in_command',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='PIC'),
        ),
        migrations.AlterField(
            model_name='total',
            name='second_in_command',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='SIC'),
        ),
        migrations.AlterField(
            model_name='total',
            name='total_time',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
    ]
