# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0086_auto_20170616_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='BySeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(default='', max_length=5)),
                ('power', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
