# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0092_auto_20170625_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_type', models.CharField(default='', max_length=5)),
                ('pilot_in_command', models.FloatField(blank=True, default=0, null=True, verbose_name='PIC')),
                ('second_in_command', models.FloatField(blank=True, default=0, null=True, verbose_name='SIC')),
            ],
        ),
    ]
