# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0107_auto_20170712_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(default='', max_length=20)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Weight',
                'ordering': ['weight'],
            },
        ),
    ]
