# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 19:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0115_auto_20170717_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='/aircraft/'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('([A-Z]{3,4})-)|([A-Z]{3,4})', 'Must be CAPITALS in a combination of ATA-ICAO')]),
        ),
    ]
