# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0119_auto_20170719_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='approaches',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Approach', verbose_name='Appr'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='registration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.TailNumber'),
        ),
    ]
