# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0123_auto_20170721_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='last_flown',
            field=models.DateField(blank=True, null=True),
        ),
    ]
