# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0130_auto_20170811_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapData',
        ),
    ]
