# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0142_auto_20170827_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='map_feature',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='aircraft/'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='landings_day',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Day Ldg'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='landings_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Night Ldg'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='total_time',
            field=models.FloatField(blank=True, default=0, verbose_name='Time'),
        ),
        migrations.AlterIndexTogether(
            name='flight',
            index_together=set([('route', 'date', 'duration')]),
        ),
        migrations.AlterIndexTogether(
            name='mapdata',
            index_together=set([('iata', 'icao')]),
        ),
    ]
