# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0147_flight_airport_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airport_json',
        ),
    ]
