# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0160_auto_20171117_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='geojson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
