# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0165_auto_20171118_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='geojson',
            new_name='route_data',
        ),
    ]
