# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0171_auto_20180119_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='ydt',
            new_name='ytd',
        ),
    ]
