# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0176_flight_duplicate_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='error',
            new_name='map_error',
        ),
    ]
