# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0179_aircraft_power_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='configuration_error',
            new_name='config_error',
        ),
    ]
