# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0180_auto_20180205_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='config_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='power_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
