# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0181_auto_20180205_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='weight_error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
