# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0186_auto_20180206_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
