# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-06 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0187_approach_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailnumber',
            name='error',
        ),
    ]
