# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0190_auto_20180807_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailnumber',
            name='aircraft_type_error',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='tailnumber',
            name='reg_error',
            field=models.NullBooleanField(),
        ),
    ]
