# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0192_auto_20180808_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailnumber',
            name='aircraft_type_error',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='tailnumber',
            name='reg_error',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='tailnumber',
            name='registration_error',
            field=models.NullBooleanField(),
        ),
    ]
