# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0206_auto_20180909_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='cross_country',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='XC'),
        ),
        migrations.AlterField(
            model_name='total',
            name='dual',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='instructor',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='CFI'),
        ),
        migrations.AlterField(
            model_name='total',
            name='instrument',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Inst'),
        ),
        migrations.AlterField(
            model_name='total',
            name='last_180',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='6mo'),
        ),
        migrations.AlterField(
            model_name='total',
            name='last_2yr',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='24'),
        ),
        migrations.AlterField(
            model_name='total',
            name='last_30',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='30'),
        ),
        migrations.AlterField(
            model_name='total',
            name='last_60',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='60'),
        ),
        migrations.AlterField(
            model_name='total',
            name='last_90',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='90'),
        ),
        migrations.AlterField(
            model_name='total',
            name='last_yr',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='12mo'),
        ),
        migrations.AlterField(
            model_name='total',
            name='night',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='pilot_in_command',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='PIC'),
        ),
        migrations.AlterField(
            model_name='total',
            name='second_in_command',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='SIC'),
        ),
        migrations.AlterField(
            model_name='total',
            name='simulated_instrument',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Sim Inst'),
        ),
        migrations.AlterField(
            model_name='total',
            name='simulator',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Sim'),
        ),
        migrations.AlterField(
            model_name='total',
            name='solo',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='total_time',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=0, max_digits=6, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='total',
            name='ytd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='YDT'),
        ),
    ]
