# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-27 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0212_auto_20180909_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='record',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Flight'),
        ),
    ]
