# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0212_auto_20180909_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
