# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0214_auto_20180919_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
