# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-05 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0215_auto_20181005_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='approaches',
        ),
    ]
