# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-26 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0225_auto_20181225_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to=flights.models.user_directory_path),
            preserve_default=False,
        ),
    ]
