# Generated by Django 2.2.8 on 2019-12-27 01:59

from django.db import migrations, models
import pdf_output.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.FileField(upload_to=pdf_output.models.user_directory_path)),
            ],
        ),
    ]
