# Generated by Django 5.2 on 2025-07-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_output', '0006_auto_20200108_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
