# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registration',
            new_name='aircraft_registration',
        ),
    ]
