# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0021_auto_20170216_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='registration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.TailNumber'),
        ),
    ]
