# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0022_flight_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='aircraft_registration',
        ),
    ]
