# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0026_flight_dummy_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='dummy_reg',
        ),
    ]
