# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0034_auto_20170507_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
