# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0042_auto_20170509_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='pilot_in_command',
            field=models.FloatField(null=True),
        ),
    ]
