# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0061_auto_20170522_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='hours',
            new_name='total_time',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='hours',
            new_name='total_time',
        ),
    ]
