# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0068_auto_20170525_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='_12_months',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='_30_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='_60_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='_6_months',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='_90_days',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
