# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0085_auto_20170614_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='total',
            options={'ordering': ['-total']},
        ),
    ]
