# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0090_power_piston'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='airline',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='121'),
        ),
        migrations.AddField(
            model_name='power',
            name='charter',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='135'),
        ),
        migrations.AddField(
            model_name='power',
            name='private',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='91'),
        ),
    ]
