# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0091_auto_20170625_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='power',
            name='charter',
        ),
        migrations.RemoveField(
            model_name='power',
            name='private',
        ),
        migrations.AlterField(
            model_name='total',
            name='landings_day',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Day Ldg'),
        ),
        migrations.AlterField(
            model_name='total',
            name='landings_night',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Night Ldg'),
        ),
        migrations.AlterField(
            model_name='total',
            name='landings_total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Ldg'),
        ),
        migrations.AlterField(
            model_name='total',
            name='simulated_instrument',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Sim Inst'),
        ),
        migrations.AlterField(
            model_name='total',
            name='simulator',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Sim'),
        ),
    ]
