# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0095_auto_20170701_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='last_2yr',
            field=models.FloatField(blank=True, null=True, verbose_name='24mo'),
        ),
    ]
