# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0098_endorsement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorsement',
            name='compleks',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='high_performance',
        ),
        migrations.RemoveField(
            model_name='endorsement',
            name='tailwheel',
        ),
    ]
