# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0099_auto_20170711_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endorsement',
            options={'ordering': ['endorsement']},
        ),
    ]
