# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0104_auto_20170712_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='is_default',
            new_name='heavy',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='large',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='medium',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='small',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='superr',
            field=models.NullBooleanField(),
        ),
    ]
