# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0105_auto_20170712_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='heavy',
            field=models.NullBooleanField(verbose_name='>255k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='large',
            field=models.NullBooleanField(verbose_name='41k-255k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='medium',
            field=models.NullBooleanField(verbose_name='12.5-41k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='small',
            field=models.NullBooleanField(verbose_name='<12,5k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='superr',
            field=models.NullBooleanField(verbose_name='Super'),
        ),
    ]
