# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0108_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'verbose_name_plural': 'Weight'},
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='heavy',
            field=models.NullBooleanField(verbose_name='Heavy >300k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='large',
            field=models.NullBooleanField(verbose_name='Large 41k-300k lbs'),
        ),
    ]
