# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0110_auto_20170712_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endorsement',
            options={'ordering': ['-total']},
        ),
    ]
