# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0113_auto_20170715_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='compleks',
            field=models.NullBooleanField(verbose_name='Complex'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='heavy',
            field=models.NullBooleanField(verbose_name='Heavy >300k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='high_performance',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='large',
            field=models.NullBooleanField(verbose_name='Large 41k-300k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='medium',
            field=models.NullBooleanField(verbose_name='Meduim 12.5-41k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='piston',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='requires_type',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='small',
            field=models.NullBooleanField(verbose_name='Small <12.5k lbs'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='superr',
            field=models.NullBooleanField(verbose_name='Super'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tailwheel',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='turbine',
            field=models.NullBooleanField(),
        ),
    ]
