# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0117_auto_20170717_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='total',
            options={'ordering': ['-total_time']},
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instrument',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0')], verbose_name='Inst'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='night',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('((?:[A-Z]{3,4}\\-?)+)', 'Must be UPPERCASE in a combination of ATA-ICAO')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulated_instrument',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0')], verbose_name='Sim Inst'),
        ),
    ]
