# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0120_auto_20170719_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['-total_time']},
        ),
    ]
