# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 22:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0122_auto_20170719_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='last_180',
            field=models.FloatField(blank=True, null=True, verbose_name='6mo'),
        ),
        migrations.AddField(
            model_name='total',
            name='last_2yr',
            field=models.FloatField(blank=True, null=True, verbose_name='24'),
        ),
        migrations.AddField(
            model_name='total',
            name='last_30',
            field=models.FloatField(blank=True, null=True, verbose_name='30'),
        ),
        migrations.AddField(
            model_name='total',
            name='last_60',
            field=models.FloatField(blank=True, null=True, verbose_name='60'),
        ),
        migrations.AddField(
            model_name='total',
            name='last_90',
            field=models.FloatField(blank=True, null=True, verbose_name='90'),
        ),
        migrations.AddField(
            model_name='total',
            name='last_yr',
            field=models.FloatField(blank=True, null=True, verbose_name='12mo'),
        ),
        migrations.AddField(
            model_name='total',
            name='ydt',
            field=models.FloatField(blank=True, null=True, verbose_name='YDT'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.1, 'Must be a positive number > 0.1')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instrument',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, 'Must be a positive number > 0.1')], verbose_name='Inst'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='night',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, 'Must be a positive number > 0.1')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulated_instrument',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, 'Must be a positive number > 0.1')], verbose_name='Sim Inst'),
        ),
    ]
