# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 17:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0124_total_last_flown'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['-role'], 'verbose_name_plural': 'Power'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instrument',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')], verbose_name='Inst'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='night',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='simulated_instrument',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')], verbose_name='Sim Inst'),
        ),
        migrations.AlterIndexTogether(
            name='flight',
            index_together=set([('route',)]),
        ),
    ]
