# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0133_auto_20170813_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='simple',
            field=models.NullBooleanField(),
        ),
    ]
