# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0143_auto_20171105_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='map_feature',
        ),
    ]
