# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0161_auto_20171117_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='geojson',
        ),
    ]
