# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 18:43
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0166_auto_20171121_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='route_data',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
