# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0167_auto_20171122_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.CharField(max_length=50),
        ),
    ]
