# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0168_auto_20171221_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='light_sport',
            field=models.NullBooleanField(verbose_name='LSA <1320 lbs'),
        ),
    ]
