# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0175_auto_20180127_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duplicate_error',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
