# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0191_auto_20180807_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailnumber',
            name='aircraft_type_error',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tailnumber',
            name='reg_error',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tailnumber',
            name='registration_error',
            field=models.NullBooleanField(default=False),
        ),
    ]
