# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-09 12:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0205_auto_20180906_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Must be a positive number > 0.1')]),
        ),
    ]
