# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-04 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0221_auto_20181015_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tailnumber',
            options={'ordering': ['aircraft'], 'verbose_name_plural': 'Tailnumbers'},
        ),
    ]
