# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-27 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0226_profile_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='upload',
            new_name='log_table',
        ),
    ]
