# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0227_auto_20190127_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='hold_number',
        ),
        migrations.AlterField(
            model_name='holding',
            name='hold',
            field=models.BooleanField(default=False),
        ),
    ]
